
title: A Robot’s Sigh
author: kaityo256
email: kaityo@users.sourceforge.jp
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kaityo256
github_username:  kaityo256
url: https://kaityo256.github.io
baseurl: ""

# Build settings
theme: minima
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

header_pages:
  - about.md  

plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 20            # 1ページの記事数
paginate_path: "/page:num/"
